name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Create dotfiles dir
      run: mkdir -p ~/dotfiles-dir

    - name: Install dotfiles
      run: HOME=~/dotfiles-dir ./install
